from lingua import Language, LanguageDetectorBuilder
from easygoogletranslate import EasyGoogleTranslate
from transformers import pipeline
import AutoModelForSequenceClassification
import AutoModelForSequenceClassification
import AutoModelForSequenceClassification
Emotion_detection("Enter your text here")
